### PR TITLE
[TECHNICAL-SUPPORT] LPS-90188 - counter proposal

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Jose. Thanks for your pull request. Did you consider a solution as simpler like this? I think it covers all the scenarios, but maybe I am missing some context.

Based on @ChrisKian 's [comment](https://issues.liferay.com/browse/PTR-591?focusedCommentId=1691942&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1691942), which I agree with, I believe this boils down to:

- If no LDAP server could authenticate, then return SUCCESS only if LDAP auth is optional or portal user export is enabled

I don't think we need to switch between the old and new behavior depending on the state of the connected LDAP directories (see [comment](https://github.com/stian-sigvartsen/liferay-portal/pull/142/commits/948297d7a0390e8e8c9c93bc39cf01e379cab8cf#r256934241))?

/cc @topolik @martamedio

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by JosemariaMunoz** [comment]
Hi @stian-sigvartsen ,

Thank you very much for review this PR.
About the proposal I think it is not that simple, you are missing one scenario: when DNE is received from preferredLDAPServerResult or other ldapServerConfigurations (so user is not exist) and none of those servers deliver a FAILURE (If exist a failure is because user exist and should not be authenticated). In this case, with your proposal, when required and export are disabled and import is enabled authentication will fail, this means that users created only in portal could not log in with their accounts, however, they should be authenticated (required is disabled).

That's why I had to add all the 'flags validation'.
Do you think this make sense for you?

Thanks again!

**Comment by stian-sigvartsen** [comment]
Hey @JosemariaMunoz . Good point, I missed that non-LDAP users now can't authenticate.

So this remaining scenario is about if the portal believes the user should be an LDAP user. If it is such a user, then in the context of authenticating this user, it should be as if LDAP is required (by configuration). Correct?

This could be achieved by changing the condition to `(authResult != SUCCESS || preferredLDAPServerId == -1)`

So the main difference between this and your solution is that yours will consider users that were created by LDAP integration as regular portal users, whenever they get removed from ALL the LDAP servers. I don't think this is desirable when LDAP is "head" (import && !export).

With my tweaked condition, user with "preferredLDAPServerId != -1" declare that this is an LDAP user and MUST be authenticated via LDAP, even if "LDAP required" is unticked.

I'll push a commit.

**Comment by JosemariaMunoz** [comment]
Hey @stian-sigvartsen ,

I think you are still missing some use cases, for example, if _authenticateAgainstPreferredLDAPServer_ returns DNE, so `preferredLDAPServerId == DNE`, and then trying to authenticate users in other LDAP servers configured, imagine that one server returns -1 (FAILURE) (I mean here: [LDAPAuth.java#L495-L519](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security/portal-security-ldap-impl/src/main/java/com/liferay/portal/security/ldap/internal/authenticator/LDAPAuth.java#L495-L519)). In this case, the authenticate method will return SUCCESS, however, one LDAP server (not preferred Server but other Server) returned FAILURE, i mean, user exists in one server and authentication was wrong. So, i think, the authenticate method should return FAILURE.

Or maybe this is the expected behavior because we should give priority to preferred LDAP Server, Is this the expected behavior? 

Thanks a lot!

**Comment by stian-sigvartsen** [comment]
Hey @JosemariaMunoz . Just to let you know we have debated that missing use case behavior in the team and we are unsure, so will need to raise with our product management in a couple of hours when the US start their work week. We will keep you updated!

**Comment by JosemariaMunoz** [comment]
Sure @stian-sigvartsen, no problem! I'll be waiting, whatever you need please let me know.
Thanks!!

**Comment by JosemariaMunoz** [comment]
Hey @stian-sigvartsen!
Do you have any update about this?
Thanks for all your help!

**Pull request closed without merging**
